import { Footer } from '../../shared/Footer'
import { MarketingHeader } from '../../shared/MarketingHeader'
import './Analytics.scss'

type AnalyticsProps = {
  onBack: () => void
}

export function Analytics({ onBack }: AnalyticsProps) {
  return (
    <main className="analytics-page" id="top">
      <MarketingHeader onGetStarted={onBack} />
      <section className="landing-hero"><div className="hero-copy"><span className="landing-eyebrow">Next-gen autonomous sourcing</span><h1>Transform<br />Procurement with <span>AI-Powered Supplier Intelligence</span></h1><p>Ditch complex spreadsheets. Automate risk assessment, accelerate onboarding, and run autonomous techno-commercial comparisons with instant AI agent insights.</p><button onClick={onBack}>Explore Platform</button></div><div className="cockpit-card"><div className="cockpit-top"><strong>▪ Procure Cockpit v2.1</strong><span>AI RUNNING</span></div><div className="cockpit-stats"><div><small>AVERAGE HEALTH</small><b>94.8%</b></div><div><small>ACTIVE ONBOARDING</small><b>3 <em>Pending</em></b></div><div><small>LIVE RFQS</small><b>7 <em>Active</em></b></div></div><div className="cockpit-savings"><small>PROJ. SAVINGS</small><strong>₹8.4L</strong><span>AI VERIFIED<br />Confidence: 96%</span></div><div className="cockpit-result"><small>AI ANALYSIS COMPLETE</small><strong>Recommended Supplier: Apex Industrial</strong><span>TECHNICAL COMPLIANCE <b>96%</b> &nbsp; COMMERCIAL SCORE <b>91%</b> &nbsp; NEGOTIATED ITEM <b>-4.2%</b></span></div></div></section>
      <section className="metric-strip"><div><strong>40%</strong><span>LESS</span><small>Manual Sourcing Work</small></div><div><strong>3×</strong><span>FASTER</span><small>Vendor Evaluation</small></div><div><strong>95%</strong><span>DATA</span><small>Verification Accuracy</small></div><div><strong>Real-time</strong><span>INSIGHTS</span><small>Sourcing Decisions</small></div></section>
      <section className="modules-section" id="platform"><span className="section-kicker">The platform suite</span><h2>Three AI-Powered Modules. One<br />Smarter Procurement Workflow.</h2><div className="module-cards"><article><span>SUPPLIER INTELLIGENCE</span><h3>Supplier Management</h3><div className="mini-panel"><p>Zenith Controls</p><small>TOTAL SPEND<br /><b>₹24.4 Crore</b></small><em>HEALTH: 87%</em></div><footer>✣ AI Insight: Consolidating Zenith shipments can improve cost-efficiency by 12%</footer></article><article><span>AI-POWERED ONBOARDING</span><h3>Advanced Onboarding</h3><div className="mini-panel"><p>Apex Industrial Onboarding <em>78% Done</em></p><div className="onboarding-progress" role="progressbar" aria-label="Apex Industrial onboarding progress" aria-valuenow={78} aria-valuemin={0} aria-valuemax={100}><span style={{ width: '78%' }} /></div><small>✓ KYC &amp; Tax Registration verified<br />✓ Technical certs parsed &amp; approved<br />✓ Commercial risk profile complete</small></div><footer>◉ AI Verification: 14 docs analyzed, 12 approved, 1 review needed</footer></article></div></section>
      <section className="comparison-preview"><div className="preview-label">Hero module</div><h2>Autonomous Techno-Commercial Comparison</h2><span className="active-pill">✣ AI procurement analyst active</span><div className="preview-table"><div><b>Supplier</b><b>Technical<br />Compliance</b><b>Commercial<br />Score</b><b>Unit Quote</b><b>Delivery Timeline</b><b>Overall AI Rank</b></div><div><span>Apex Industrial</span><span>96.4%</span><span>91.2%</span><strong>₹16,200</strong><span>14 Days</span><em>RANK 1 (94.3%)</em></div><div><span>Zenith Controls</span><span>89.0%</span><span>94.5%</span><strong>₹19,500</strong><span>10 Days</span><em>RANK 2 (88.7%)</em></div><div><span>Vortex Equipments</span><span>92.1%</span><span>84.0%</span><strong>₹17,800</strong><span>21 Days</span><em>RANK 3 (80.7%)</em></div></div><div className="preview-insight">✣ <strong>AI Recommendation: Select Apex Industrial</strong><span>Apex provides the optimal tradeoff of technical compliance (96.4%) and price to delivery reliability.</span></div></section>
      <section className="workflow-section" id="how-it-works"><span className="section-kicker">The step-by-step workflow</span><h2>From Supplier Discovery to Confident Decisions</h2><div className="workflow-row">{['Manage Suppliers', 'Onboard & Verify', 'Collect Quotes', 'AI Analysis', 'Compare & Decide'].map((title, index) => <article key={title}><strong>0{index + 1}</strong><h3>{title}</h3><p>{['Build automatic 360-degree digital profiles of existing and potential suppliers.', 'AI extracts data from tax records, certificates, and compliance registries.', 'Automate dynamic quoting processes through pre-formatted vendor templates.', 'Instantly perform deep techno-commercial evaluations across five variables.', 'Execute transparent contracts supported by verified insights.'][index]}</p></article>)}</div></section>
      <section className="core-section" id="ai-decision-engine"><span className="section-kicker">Under the hood</span><h2>From Data to Procurement Decisions</h2><div className="core-flow"><div><small>DATA INGESTION</small><span>● ERP Master Data</span><span>● Email Attachments</span><span>● PDF Commercial Quotes</span><span>● Regulatory Web Registers</span><span>● Historical Vendor Performance</span></div><div className="core-box"><b>✣</b><strong>Procure.AI Core</strong><p>Deep-learning models track supplier commercial parameters, financial risks, and past performance metrics.</p></div><div><small>RESOLVED INSIGHTS</small><span>● Technical Scoring Insights</span><span>● Commercial Extraction &amp; Risk</span><span>● Dynamic Delivery Probability</span><span>● Best Negotiated Price-target</span></div></div></section>
      <section className="operations-section" id="solutions"><span className="section-kicker">Live procurement metrics</span><h2>Everything Procurement Needs. In One View.</h2><div className="operations-card"><div className="operation-stats"><div><small>REGISTERED SUPPLIERS</small><b>247 Active</b></div><div><small>LIVE RFQS FOR QUOTES</small><b>18 Open RFQs</b></div><div><small>ONBOARDING IN PROGRESS</small><b>12 Vendors</b></div><div><small>CONFIDENTIAL AI SAVINGS</small><b>₹24.6 Lakhs</b></div></div><div className="operation-body"><div className="lifecycle-panel"><strong>Onboarding Pipeline Lifecycle</strong><div className="lifecycle-item"><div><span>Global Coatings</span><b>82%</b></div><div className="lifecycle-track"><i style={{ width: '82%' }} /></div><small>Document verification</small></div><div className="lifecycle-item"><div><span>Techno CNC &amp; Dies</span><b>64%</b></div><div className="lifecycle-track"><i style={{ width: '64%' }} /></div><small>Technical compliance review</small></div><div className="lifecycle-item"><div><span>Precision Fasteners Corp</span><b>38%</b></div><div className="lifecycle-track"><i style={{ width: '38%' }} /></div><small>Initial supplier registration</small></div></div><div><strong>❗ 3 Decisions Need Attention</strong><p>Due RFQ ready for Apex Industrial verification</p><p>Auto-negotiate target discount found</p><p>Document mismatch detected in Zenith registration form</p></div></div></div></section>
      <section className="benefits-section"><span className="section-kicker">Why Procure.AI</span><h2>Transform Your Procurement Operations</h2><div>{[['◉', 'Less Manual Work', 'Automate heavy-lifting tasks like data entry, manual risk scoring, and due diligence.'], ['▥', 'Better Supplier Decisions', 'Evaluate technical compliance and pricing trends using multiple parameters.'], ['ϟ', 'Faster Procurement Cycles', 'Shorten vendor registration, RFQ collection, and techno-commercial analysis.']].map(([icon, title, text]) => <article key={title}><b>{icon}</b><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <Footer />
    </main>
  )
}
